config/routes.rb
Loomio::Application.routes.draw do

  slug_regex = /[a-z0-9\-\_]*/i

  ActiveAdmin.routes(self)

  namespace :admin do
    namespace :stats do
      get :group_metrics
      get :retention
      get :events
      get :weekly_activity
    end
  end

  namespace :api, path: '/api/v1' do
    resources :comments, only: :create
  end


  get "/explore", to: 'explore#index', as: :explore
  get "/explore/search", to: "explore#search", as: :search_explore
  get "/explore/category/:id", to: "explore#category", as: :category_explore

  resource :search, only: :show

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }


  get "/contacts/:importer/callback" => "users/contacts#callback"

  namespace :inbox do
    get   '/', action: 'index'
    get   'size'
    get   'preferences'
    put 'update_preferences'
    match 'mark_as_read', via: [:get, :post]
    match 'mark_all_as_read/:id', action: 'mark_all_as_read', as: :mark_all_as_read, via: [:get, :post]
    match 'unfollow', via: [:get, :post]
  end

  resources :group_requests, only: [:create, :new] do
    get :confirmation, on: :collection
  end

  resources :invitations, only: [:show, :create, :destroy]

  get "/theme_assets/:id", to: 'theme_assets#show', as: 'theme_assets'

  resources :groups, path: 'g', only: [:new, :create, :edit, :update] do
    member do
      post :follow
      post :unfollow
      post :join
      post :add_members
      post :hide_next_steps
      get :add_subgroup
      post :email_members
      post :edit_description
      delete :leave_group
      get :members_autocomplete
    end

    resources :motions,     only: [:index]
    resources :discussions, only: [:index, :new]
    resources :invitations, only: [:new, :destroy]

    scope module: :groups do
      resources :memberships, only: [:index, :edit, :destroy, :new, :create] do
        member do
         post :make_admin
         post :remove_admin
        end
      end

      scope controller: 'group_setup' do
        member do
          get :setup
          put :finish
        end
      end

      resources :membership_requests, only: [:create, :new]
      get :membership_requests,  to: 'manage_membership_requests#index', as: 'manage_membership_requests'
    end
  end

  scope module: :groups do
    resources :manage_membership_requests, only: [], as: 'membership_requests' do
      member do
        post :approve
        post :ignore
      end
    end
  end

  scope module: :groups, path: 'g', slug: slug_regex do
    get    ':id(/:slug)', action: 'show' #, as: :group
    patch    ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'
    post 'archive/:id',  action: 'archive', as: :archive_group
  end

  constraints(GroupSubdomainConstraint) do
    get '/' => 'groups#show'
    patch '/' => 'groups#update'
  end

  constraints(MainDomainConstraint) do
    root :to => 'marketing#index'
  end

  delete 'membership_requests/:id/cancel', to: 'groups/membership_requests#cancel', as: :cancel_membership_request

  resources :motions, path: 'm', only: [:new, :create, :edit, :index] do
    resources :votes, only: [:new, :create, :update]
    member do
      get :history
      patch :close
      patch :create_outcome
      patch :update_outcome
    end
  end

  scope module: :motions, path: 'm', slug: slug_regex do
    get    ':id(/:slug)', action: 'show', as: :motion
    patch  ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'
  end

  resources :discussions, path: 'd', only: [:new, :edit, :create] do
    get :activity_counts, on: :collection
    resources :invitations, only: [:new]

    member do
      post :follow
      post :unfollow
      post :update_description
      post :update
      post :add_comment
      post :show_description_history
      get :new_proposal
      post :move
    end
  end

  scope module: :discussions, path: 'd', slug: slug_regex do
    get    ':id(/:slug)', action: 'show' #,    as: :discussion
    patch  ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'

    post ':id/preview_version/(:version_id)', action: 'preview_version', as: 'preview_version_discussion'
    post 'update_version/:version_id',        action: 'update_version',   as: 'update_version_discussion'
  end

  resources :comments , only: [:destroy, :edit, :update, :show] do
    post :like, on: :member
  end

  resources :attachments, only: [:create, :new] do
    collection do
      get 'sign'
      get :iframe_upload_result
    end
  end

  resources :notifications, :only => :index do
    collection do
      get :groups_tree_dropdown
      get :dropdown_items
      post :mark_as_viewed
    end
  end

  get '/localisation/datetime_input_translations' => 'localisation#datetime_input_translations', format: 'js'

  resources :users, path: 'u', only: [:new] do
    member do
      put :set_avatar_kind
      post :upload_new_avatar
      post :dismiss_system_notice
    end
  end

  namespace :email_actions do
    get   'unfollow_discussion/:discussion_id/:unsubscribe_token', action: 'unfollow_discussion', as: :unfollow_discussion
    get   'mark_summary_email_as_read', action: 'mark_summary_email_as_read', as: :mark_summary_email_as_read
    get   'mark_discussion_as_read/:discussion_id/:event_id/:unsubscribe_token', action: 'mark_discussion_as_read', as: :mark_discussion_as_read
  end

  scope module: :users do
    match '/profile',          action: 'profile', as: :profile, via: [:get, :post]
    get 'import_contacts' => 'contacts#import'
    get 'autocomplete_contacts' => 'contacts#autocomplete'

    scope module: :email_preferences do
      get   '/email_preferences', action: 'edit',   as: :email_preferences
      put   '/email_preferences', action: 'update', as: :update_email_preferences
    end

    scope module: :change_password do
      get '/change_password', action: 'show'
      post '/change_password', action: 'update'
    end

    scope module: :user_deactivation_responses do
      post '/user_deactivation_responses', action: 'create'
    end
  end

  scope module: :users, path: 'u' do
    get ':id(/:slug)', action: 'show',    slug: slug_regex, as: :user
    patch ':id(/:slug)', action: 'update',  slug: slug_regex
    post ':id(/:slug)', action: 'deactivate', slug: slug_regex
  end

  get '/deactivation_instructions' => 'users#deactivation_instructions'
  get '/about_deactivation' => 'users#about_deactivation'

  match '/announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement', via: [:get, :post]
  post '/translate/:model/:id', to: 'translations#create', as: :translate

  get '/users/invitation/accept' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('invitation_token=','')}"}
  get '/group_requests/:id/start_new_group' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('token=','')}"}

  get '/contributions' => redirect('/crowd')
  get '/contributions/thanks' => redirect('/crowd')
  get '/contributions/callback' => redirect('/crowd')
  get '/crowd' => redirect('https://love.loomio.org/')
  get '/groups' => redirect('/explore')

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  constraints(MainDomainConstraint) do
    scope controller: 'pages' do
      get :about
      get :privacy
      get :purpose
      get :services
      get :terms_of_service
      get :third_parties
      get :try_it
      get :translation
      get :wallets
      get :browser_not_supported
    end
  end

  constraints(GroupSubdomainConstraint) do
    get '/about' => redirect('https://www.loomio.org/about')
    get '/privacy' => redirect('https://www.loomio.org/privacy')
    get '/purpose' => redirect('https://www.loomio.org/purpose')
    get '/services' => redirect('https://www.loomio.org/services')
    get '/terms_of_service' => redirect('https://www.loomio.org/terms_of_service')
    get '/third_parties' => redirect('https://www.loomio.org/third_parties')
    get '/try_it' => redirect('https://www.loomio.org/try_it')
    get '/wallets' => redirect('https://www.loomio.org/wallets')
  end

  scope controller: 'help' do
    get :help
  end

  get '/detect_locale' => 'detect_locale#show'

  resources :contact_messages, only: [:new, :create]
  get 'contact(/:destination)', to: 'contact_messages#new'

  #redirect from wall to new group signup
  namespace :group_requests do
    get 'selection', action: 'new'
    get 'subscription', action: 'new'
    get 'pwyc', action: 'new'
  end

  get '/discussions/:id', to: 'discussions_redirect#show'
  get '/groups/:id',      to: 'groups_redirect#show'
  get '/motions/:id',     to: 'motions_redirect#show'

  get '/users/invitation/accept' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('invitation_token=','')}"}
  get '/group_requests/:id/start_new_group' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('token=','')}"}

  get '/contributions'      => redirect('/crowd')
  get '/contributions/thanks' => redirect('/crowd')
  get '/contributions/callback' => redirect('/crowd')
  get '/crowd'              => redirect('https://love.loomio.org/')

  scope path: 'pages' do
    get 'home'         => redirect('/')
    get 'how*it*works' => redirect('/purpose#how-it-works')
    get 'get*involved' => redirect('/about')
    get 'privacy'      => redirect('/privacy_policy')
    get 'about'        => redirect('/about#about-us')
    match 'contact'    => 'contact_messages#new', via: [:get, :post]
  end

  get '/get*involved'       => redirect('/purpose#how-it-works')
  get '/how*it*works'       => redirect('/purpose#how-it-works')
  get '/about#how-it-works' => redirect('/purpose#how-it-works')

  get '/blog'       => redirect('http://blog.loomio.org')
  get '/press'      => redirect('http://blog.loomio.org/press-pack')

app/helpers/discussions_helper.rb
module DiscussionsHelper
  include Twitter::Extractor
  include Twitter::Autolink

  def filter_discussion_events(activity)
    last_item = nil
    ignored_event_kinds = %w[motion_closing_soon user_mentioned comment_liked]
    deduplicate_kinds = %w[discussion_description_edited discussion_title_edited motion_close_date_edited]

    activity.
      reject {|item| ignored_event_kinds.include? item.kind }.
      map do |item|
      next if last_item &&
              deduplicate_kinds.include?(item.kind) &&
              item.user == last_item.user && item.kind == last_item.kind
      last_item = item
    end.compact
  end

  def no_discussions_available?
    (@discussion_readers_with_open_motions.size + @discussion_readers_without_open_motions.size) == 0
  end

  def enough_activity_for_jump_link?
    @discussion.items_count > 3
  end

  def path_of_latest_activity
    if current_page == @discussion_reader.first_unread_page
      '#latest-activity'.html_safe
    else
      discussion_path(@discussion, page: @discussion_reader.first_unread_page, anchor: 'latest-activity')
    end
  end

  def path_of_add_comment
    if current_page == actual_total_pages
      '#comment-input'
    else
      if actual_total_pages == 1
        discussion_path(@discussion, anchor: 'comment-input')
      else
        discussion_path(@discussion, page: actual_total_pages, anchor: 'comment-input')
      end
    end
  end

  def xml_item(event)
    case event.kind.to_sym
    when :new_comment then event.eventable
    #else                   DiscussionItem.new event
    end
  end

  def css_classes_for_discussion_preview(discussion, discussion_reader)
    class_names = []
    class_names << 'showing-group' unless @group == discussion.group
    class_names << 'unread' if discussion_reader.unread_content_exists?
    class_names.join(' ')
  end

  def add_mention_links(comment)
    auto_link_usernames_or_lists(comment, :username_url_base => "#", :username_include_symbol => true)
  end

  def css_for_markdown_link(target, setting)
    return "icon-ok" if (target.uses_markdown? == setting)
  end

  def markdown_img(uses_markdown)
    if uses_markdown
      image_tag("markdown_on.png", class: 'markdown-icon markdown-on')
    else
      image_tag("markdown_off.png", class: 'markdown-icon markdown-off')
    end
  end

  def last_page?
    actual_total_pages == current_page
  end

  def actual_total_pages
    if @activity.total_pages == 0
      1
    else
      @activity.total_pages
    end
  end

  def current_page
    @current_page ||= requested_or_first_unread_page
  end

  def requested_or_first_unread_page
    if params[:page]
      params[:page].to_i
    else
      @discussion_reader.first_unread_page
    end
  end

  def user_has_not_read_event?(event)
    if @discussion_reader.last_read_at.present?
      if event.belongs_to?(current_user)
        false
      else
        @discussion_reader.last_read_at < event.updated_at
      end
    else
      false
    end
  end

  def discussion_privacy_collection(discussion)
    options = []

    public_description = t('discussion_form.privacy.will_be_public')
    if discussion.group.present?
      private_description = t('discussion_form.privacy.will_be_private_to_group', group_name: discussion.group_name)
    else
      private_description = t('discussion_form.privacy.will_be_private')
    end

    options << ["<i class='fa fa-globe'></i>#{t(:'common.public')}:
                  #{public_description}".html_safe, false]

    options << ["<i class='fa fa-lock'></i>#{t(:'common.private')}:
                 #{private_description}".html_safe, true ]
  end

  def privacy_language(discussion)
    discussion.private? ? "private" : "public"
  end

  def privacy_icon(discussion)
    discussion.private? ? "lock" : "globe"
  end
end

app/views/discussions/_activity.html.haml
%ul#activity-list
  .top-pagination
    = link_to_previous_page items, "Show earlier comments"

  -marked_first_unread = false
  - filter_discussion_events(items).each do |event|
    - next if event.kind == 'new_discussion'
    -unless @discussion_reader.first_read?
      - unless marked_first_unread
        - unless @discussion_reader.has_read?(event)
          - unless event.belongs_to? current_user_or_visitor
            - marked_first_unread = true
            .shifted_anchor#latest-activity
            .dog-ear#js-dog-ear.js-tooltip{title: t(:'read_up_to')}
              &nbsp;
            .new-activity-divider

    %li.activity-item-container
      - if event.kind == 'new_comment'
        = render event.eventable
      - else
        - discussion_item = DiscussionItem.new(event)
        = render 'discussion_item', :item => discussion_item

app/views/discussions/_add_comment.html.haml
- if last_page?
  = form_tag add_comment_discussion_path(discussion), :remote => true, id: "new-comment-form" do
    = hidden_field_tag 'authenticity_token', form_authenticity_token
    = render 'avatar', user: current_user_or_visitor
    #comment-input{ data: {group: @group.id, autocomplete_path: members_autocomplete_group_path(@group) } }
      .form-container
        = text_area_tag 'comment', "", id: 'new-comment', class: 'js-warn-before-navigating-away', placeholder: t(:comment_form_placeholder)
        #attachment-container

      = hidden_field_tag 'uses_markdown', @uses_markdown, {id: 'global-uses-markdown'}
      = submit_tag t(:comment_form_submit_button), class: "btn btn-primary submit", id: 'post-new-comment', :data => {:disable_with => t(:comment_form_submit_button)}
    - if user_signed_in?
      .comment-toolbar
        -unless browser.ie? && browser.version.to_i < 10
          .attachment-icon#add-attachment-icon
        .dropdown#comment-markdown-dropdown.global-markdown-setting
          %a.dropdown-toggle{href:'#comment-markdown-dropdown', id:'comment-markdown-dropdown-link', 'data-toggle'=> 'dropdown'}
            = markdown_img(@uses_markdown)
          = render 'markdown_setting', target: current_user_or_visitor

  - if user_signed_in?
    -unless browser.ie? && browser.version.to_i < 10
      = s3_uploader_form post: attachments_url, as: "attachment[location]", redirect_url: iframe_upload_result_attachments_url do
        = file_field_tag :file, multiple: true

      %script#template-upload-in-progress{type: "text/x-tmpl"}
        .attachment-uploader
          .uploading-filename
            {%=o.name%}
          %button.close.cancel-upload &times;
          .progress.active
            .progress-bar

      %script#template-upload--attached{type: "text/x-tmpl"}
        .attachments
          .attachment-success{data: { 'attachment-id' => "{%=o.id%}" } }
            = link_to "{%=o.name%}", "{%=o.location%}", target: "_blank"
            ({%= (parseInt(o.size) / (1024*1024)).toFixed(2) + " MB" %})
            %button.close.remove-attachment &times;

      %script#template-upload--comment-input{type: "text/x-tmpl"}
        %input{type: 'hidden', name: "attachments[]", value: '{%=o.id%}', data: { 'attachment-id' => "{%=o.id%}" }}

app/views/discussions/_description_history.html.haml
.modal-dialog
  .modal-content
    .modal-header
      %button.close{"data-dismiss" => "modal"}×
      %h2= t "description_history.header"
    .modal-body
      .revision-title
        %h3= @discussion.title
        %p
          = t("description_history.edited_by", when: time_ago_in_words(@discussion.last_versioned_at), who: @originator.name)
          %em
            = " "
            -if @discussion.live?
              =t "description_history.current"
            -else
              =link_to t("description_history.restore"), update_version_discussion_path(@discussion.version), :method => :post, :class => "", :id => "revert-to-version", :data => { :disable_with => t("description_history.applying_changes") }
      .revision-version
        %h3= t "description_history.subheader"
        %p
          -if @discussion.has_previous_versions?
            =link_to t("description_history.previous"), preview_version_discussion_path(@discussion, @discussion.previous_version.version), :method => :post, :id => "discussion-previous-version", :remote => true
          -else
            =link_to t("description_history.previous"), "#", :class => "disabled"
          =" | "
          -if @discussion.next_version.present?
            =link_to t("description_history.next"), preview_version_discussion_path(@discussion, @discussion.next_version.version), :method => :post, :id => "discussion-next-version", :remote => true
          -elsif !(@discussion.live?)
            =link_to t("description_history.next"), preview_version_discussion_path(@discussion), :method => :post, :remote => true
          -else
            =link_to t("description_history.next"), "#", :class => "disabled"
      .revision-content
        %p= render_rich_text(@discussion.description, @discussion.uses_markdown)
    .modal-footer
      = link_to t(:close), "#", "data-dismiss" => "modal", class: "btn btn-primary"

app/views/discussions/_discussion_context.html.haml
.row
  .col-sm-8
    .description-container
      .description-body
        .long-description
          = render_rich_text(@discussion.description, @discussion.uses_markdown)
        .translation-spacer.translated
        .translated-description.translated
          = t(:loading_translation)
        - if can?(:edit, @discussion)
          = link_to edit_discussion_path(@discussion) do
            %i.fa.fa-pencil
            = t :edit
        - if TranslationService.can_translate? @discussion
          = translate_link_for @discussion
  .col-sm-3.col-sm-offset-1.right-context
    .discussion-additional-info
      = t("discussion_context.started_html",
          when: time_ago_in_words(@discussion.created_at),
          who: @discussion.author.name,
          link: user_path(@discussion.author),
          link_class: 'user-name')
      -if @discussion.has_previous_versions?
        .last-edited-by
          = link_to t(:"common.edited", when: time_ago_in_words(@discussion.last_versioned_at)), show_description_history_discussion_path(@discussion), :method => :post, :class => "see-description-history", :remote => true
      - if can? :follow, @discussion
        .following-status
          - if @discussion_reader.following?
            = link_to unfollow_discussion_path(@discussion), method: :post, class: "btn btn-default js-tooltip cuke-unfollow", title: t(:"discussion_context.click_to_unfollow") do
              %i.fa.fa-volume-up
              = t :"common.following"
            %p= t :"discussion_context.following_details"
          - else
            = link_to follow_discussion_path(@discussion), method: :post, class: "btn btn-default js-tooltip cuke-follow", title: t(:"discussion_context.click_to_follow") do
              %i.fa.fa-volume-down
              = t :"common.not_following"
            %p= t :"discussion_context.not_following_details"


#description-revision-history.modal

app/views/discussions/_discussion_item.html.haml
.activity-item-body.translate-parent
  %div{:class => "activity-icon " + item.icon }
  %span.activity-item-actor
    - unless item.actor.blank?
      =link_to item.actor.name, user_path(item.actor), class: "user-name"
  %span.activity-item-header= item.header
  %span.activity-item-content.word-break= item.body
  .activity-item-time
    = t(:ago, :quantity_of_time => time_ago_in_words(item.time))

app/views/discussions/_discussion_list.html.haml
%section.main-content
  - if @discussions.any?
    .discussions
      - discussions_with_motions = @discussions.select(&:current_motion)
      - if discussions_with_motions.any?
        %ul.selector-list.bordered#discussions-with-motions
          - discussions_with_motions.each do |discussion|
            %li.selector-item= render '/discussions/discussion_preview', discussion: discussion
      %ul.selector-list.bordered#discussions-without-motions
        - @discussions.select{|d| d.current_motion.nil? }.each do |discussion|
          %li.selector-item= render '/discussions/discussion_preview', discussion: discussion

    .text-center= paginate @discussions, :window => 3

  -else
    - # no discussions visible
    - if sifting_unread? or sifting_followed?
      =(t :'discussion_list.empty.no_discussions_matching_filters_html', link: dashboard_path)
    - else
      - if @group
        - if @group.public_discussions_only?
          - # there are no discussions
          = t(:'discussion_list.empty.no_discussions_in_group')

        - else
          - # there might be private discussions
          - if can?(:see_private_content, @group)
            - # there are no discussions in the group at all
            = t(:'discussion_list.empty.no_discussions_in_group')
          -else
            - # explain why the list is empty
            - if @group.private_discussions_only?
              = t :'discussion_list.empty.discussions_are_private'
            - else
              = t :'discussion_list.empty.no_public_discussions'

            - # explain how one becomes a member
            - if @group.membership_granted_upon_approval?
              = t :'discussion_list.empty.request_membership_html', href: new_group_membership_request_path(@group)
            - elsif @group.members_can_add_members?
              = t :'discussion_list.empty.membership_is_invitation_only'
            - else
              = t :'discussion_list.empty.membership_is_invitation_by_admin_only'

            - # invite them to login
            - unless current_user_or_visitor.is_logged_in?
              = t(:'discussion_list.empty.log_in_html', href: new_user_session_path)

      - else # dashboard
        - # there are no discussions in any of your groups
        = t(:'discussion_list.empty.no_discussions')

app/views/discussions/_discussion_preview.html.haml
- discussion_reader = @discussion_reader_cache.get_for(discussion)
- unread_comments_count = discussion_reader.unread_comments_count
- motion = discussion.current_motion
- motion_reader = @motion_reader_cache.get_for(motion) if motion
- last_vote = @last_vote_cache.get_for(motion) if motion
.clearfix
  %div.discussion-preview{ class: css_classes_for_discussion_preview(discussion, discussion_reader) }
    %a.selector-discussion-link{ href: discussion_path(discussion) }
      - if user_signed_in? && motion
        .vote-icon
          - if can?(:vote, motion)
            .activity-icon{class: "position-#{last_vote.position}-icon"}

      .discussion-title
        = discussion.title
        - if @group.nil?
          .group-name
            - if discussion.group.is_subgroup?
              = discussion.group.parent.name
              %span.name-separator
                ▶
            = discussion.group.name

        - elsif @group != discussion.group
          .group-name= discussion.group_name

      - if motion
        .icon.shim{:id => "graph_#{motion.id}"}
          .motion-sparkline
            = motion_sparkline(motion)
          - if motion.voting? && motion_reader.unread_activity_count > 0
            %span.activity-count.label.label-info
              = motion_reader.unread_activity_count
      - else
        .large-icon.pie-icon.activity-icon

      - if unread_comments_count == 0
        .large-icon.discussion-icon.activity-icon.disabled-icon
      -else
        .large-icon.discussion-icon.activity-icon.enabled-icon
          %span.activity-count.label.label-info.unread-comments-count
            = unread_comments_count

      .discussion-date-info.hidden-xs
        -if motion
          .proposal-close-date= t( :time_until_close, quantity_of_time: time_ago_in_words(motion.closing_at) )
        - else
          .latest-comment-time= t( :ago, quantity_of_time: time_ago_in_words(discussion.last_comment_at) )

app/views/discussions/_options.html.haml
.dropdown#discussion-options
  %a.dropdown-toggle{href:"#", id: "options-dropdown", 'data-toggle' => 'dropdown'}
    %i.fa.fa-cog
  %ul.dropdown-menu.pull-right
    - if can?(:edit, discussion)
      %li= link_to t(:edit_discussion), edit_discussion_path, class: 'edit-discussion'
    - if can?(:move, @discussion)
      %li= link_to t(:move_discussion), '#move-discussion-modal', "data-toggle" => "modal", id: 'move-discussion'
    -if can? :destroy, discussion
      %li= link_to t(:delete_discussion), discussion_path(discussion), method: :delete, data: { confirm: t(:confirm_delete_discussion) }

- if can?(:move, @discussion)
  #move-discussion-modal.modal
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"data-dismiss" => "modal"}×
          %h3= t :move_discussion_where
        = form_tag move_discussion_path(discussion), method: :post, 
          data: { public_group_ids: destination_ids_for(discussion, current_user, :public),
                  hidden_group_ids: destination_ids_for(discussion, current_user, :private),
                  private_discussion: @discussion.private ? 1 : 0 }, 
          class: 'move-discussion-form' do
          .modal-body
            = select_tag :destination_group_id, options_for_select(@destination_groups.map{|g| [g.full_name, g.id]}), class: 'form-control'
          .warn-move.warn-move-will-make-private{style: "display: none"}
            %i.fa.fa-lock
            = t(:move_discussion_to_hidden_group)
          .warn-move.warn-move-will-make-public{style: "display: none"}
            %i.fa.fa-unlock
            = t(:move_discussion_to_public_group)
          .modal-footer
            = submit_tag t(:move_discussion), class: "btn btn-info", id: 'move-discussion-submit', :data => { :disable_with => t(:'move_discussion') }
            = link_to t(:cancel), "#", "data-dismiss" => "modal", class: "btn btn-default"

app/views/discussions/_prompt_logged_in_user_to_join_modal.html.haml
.modal#prompt-user-to-join-or-authenticate
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal"} ×
        %h3= t :"prompt_user_to_join.header"
      .modal-body
        %p= t :"prompt_user_to_join.body"
      .modal-footer
        =join_group_button(@group, class: "btn btn-lg btn-primary", id: "align-button")

= render 'discussions/js_prompt_user_to_join_or_authenticate'

app/views/discussions/_prompt_logged_out_user_to_authenticate_or_signup_modal.html.haml
.modal#prompt-user-to-join-or-authenticate
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal"}×
        %h3= t :"prompt_visitor_to_authenticate.header"
      .modal-body
        %p= t :"prompt_visitor_to_authenticate.body"
        %p= t :"prompt_user_to_join.body"
      .modal-footer
        .row
          .col-md-6=link_to t(:log_in), new_user_session_path, class: "btn btn-block btn-success"
          .col-md-6=join_group_button(@group, id: "align-button")

= render 'discussions/js_prompt_user_to_join_or_authenticate'

app/views/discussions/add_comment.js.erb
$("#new-comment").val('');
$("ul#activity-list").append("<li class='activity-item-container'><%=escape_javascript(render @comment)%></li>");

$('.attachment-success').remove()
$('#new-comment-form').find("input[name='attachments[]']").remove()

app/views/discussions/discussion_translations.js.erb
title = "<%= get_translation @translation, :title %>";
description = "<%= get_translation @translation, :description %>";
$('.discussion-header-container').find('.discussion-title-translation').html(title);
$('#discussion-context').find('.translated-description').html(description);

app/views/discussions/new.html.haml
.page-container
  = render '/groups/title'
  %h2= t "discussion_form.new.header"

  = render "/discussions/form", :discussion => @discussion, :user_groups => @user_groups