config/routes.rb
Loomio::Application.routes.draw do

  slug_regex = /[a-z0-9\-\_]*/i

  ActiveAdmin.routes(self)

  namespace :admin do
    namespace :stats do
      get :group_metrics
      get :retention
      get :events
      get :weekly_activity
    end
  end

  namespace :api, path: '/api/v1' do
    resources :comments, only: :create
  end


  get "/explore", to: 'explore#index', as: :explore
  get "/explore/search", to: "explore#search", as: :search_explore
  get "/explore/category/:id", to: "explore#category", as: :category_explore

  resource :search, only: :show

  devise_for :users, controllers: { sessions: 'users/sessions',
                                    registrations: 'users/registrations',
                                    omniauth_callbacks: 'users/omniauth_callbacks' }


  get "/contacts/:importer/callback" => "users/contacts#callback"

  namespace :inbox do
    get   '/', action: 'index'
    get   'size'
    get   'preferences'
    put 'update_preferences'
    match 'mark_as_read', via: [:get, :post]
    match 'mark_all_as_read/:id', action: 'mark_all_as_read', as: :mark_all_as_read, via: [:get, :post]
    match 'unfollow', via: [:get, :post]
  end

  resources :group_requests, only: [:create, :new] do
    get :confirmation, on: :collection
  end

  resources :invitations, only: [:show, :create, :destroy]

  get "/theme_assets/:id", to: 'theme_assets#show', as: 'theme_assets'

  resources :groups, path: 'g', only: [:new, :create, :edit, :update] do
    member do
      post :follow
      post :unfollow
      post :join
      post :add_members
      post :hide_next_steps
      get :add_subgroup
      post :email_members
      post :edit_description
      delete :leave_group
      get :members_autocomplete
    end

    resources :motions,     only: [:index]
    resources :discussions, only: [:index, :new]
    resources :invitations, only: [:new, :destroy]

    scope module: :groups do
      resources :memberships, only: [:index, :edit, :destroy, :new, :create] do
        member do
         post :make_admin
         post :remove_admin
        end
      end

      scope controller: 'group_setup' do
        member do
          get :setup
          put :finish
        end
      end

      resources :membership_requests, only: [:create, :new]
      get :membership_requests,  to: 'manage_membership_requests#index', as: 'manage_membership_requests'
    end
  end

  scope module: :groups do
    resources :manage_membership_requests, only: [], as: 'membership_requests' do
      member do
        post :approve
        post :ignore
      end
    end
  end

  scope module: :groups, path: 'g', slug: slug_regex do
    get    ':id(/:slug)', action: 'show' #, as: :group
    patch    ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'
    post 'archive/:id',  action: 'archive', as: :archive_group
  end

  constraints(GroupSubdomainConstraint) do
    get '/' => 'groups#show'
    patch '/' => 'groups#update'
  end

  constraints(MainDomainConstraint) do
    root :to => 'marketing#index'
  end

  delete 'membership_requests/:id/cancel', to: 'groups/membership_requests#cancel', as: :cancel_membership_request

  resources :motions, path: 'm', only: [:new, :create, :edit, :index] do
    resources :votes, only: [:new, :create, :update]
    member do
      get :history
      patch :close
      patch :create_outcome
      patch :update_outcome
    end
  end

  scope module: :motions, path: 'm', slug: slug_regex do
    get    ':id(/:slug)', action: 'show', as: :motion
    patch  ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'
  end

  resources :discussions, path: 'd', only: [:new, :edit, :create] do
    get :activity_counts, on: :collection
    resources :invitations, only: [:new]

    member do
      post :follow
      post :unfollow
      post :update_description
      post :update
      post :add_comment
      post :show_description_history
      get :new_proposal
      post :move
    end
  end

  scope module: :discussions, path: 'd', slug: slug_regex do
    get    ':id(/:slug)', action: 'show' #,    as: :discussion
    patch  ':id(/:slug)', action: 'update'
    delete ':id(/:slug)', action: 'destroy'

    post ':id/preview_version/(:version_id)', action: 'preview_version', as: 'preview_version_discussion'
    post 'update_version/:version_id',        action: 'update_version',   as: 'update_version_discussion'
  end

  resources :comments , only: [:destroy, :edit, :update, :show] do
    post :like, on: :member
  end

  resources :attachments, only: [:create, :new] do
    collection do
      get 'sign'
      get :iframe_upload_result
    end
  end

  resources :notifications, :only => :index do
    collection do
      get :groups_tree_dropdown
      get :dropdown_items
      post :mark_as_viewed
    end
  end

  get '/localisation/datetime_input_translations' => 'localisation#datetime_input_translations', format: 'js'

  resources :users, path: 'u', only: [:new] do
    member do
      put :set_avatar_kind
      post :upload_new_avatar
      post :dismiss_system_notice
    end
  end

  namespace :email_actions do
    get   'unfollow_discussion/:discussion_id/:unsubscribe_token', action: 'unfollow_discussion', as: :unfollow_discussion
    get   'mark_summary_email_as_read', action: 'mark_summary_email_as_read', as: :mark_summary_email_as_read
    get   'mark_discussion_as_read/:discussion_id/:event_id/:unsubscribe_token', action: 'mark_discussion_as_read', as: :mark_discussion_as_read
  end

  scope module: :users do
    match '/profile',          action: 'profile', as: :profile, via: [:get, :post]
    get 'import_contacts' => 'contacts#import'
    get 'autocomplete_contacts' => 'contacts#autocomplete'

    scope module: :email_preferences do
      get   '/email_preferences', action: 'edit',   as: :email_preferences
      put   '/email_preferences', action: 'update', as: :update_email_preferences
    end

    scope module: :change_password do
      get '/change_password', action: 'show'
      post '/change_password', action: 'update'
    end

    scope module: :user_deactivation_responses do
      post '/user_deactivation_responses', action: 'create'
    end
  end

  scope module: :users, path: 'u' do
    get ':id(/:slug)', action: 'show',    slug: slug_regex, as: :user
    patch ':id(/:slug)', action: 'update',  slug: slug_regex
    post ':id(/:slug)', action: 'deactivate', slug: slug_regex
  end

  get '/deactivation_instructions' => 'users#deactivation_instructions'
  get '/about_deactivation' => 'users#about_deactivation'

  match '/announcements/:id/hide', to: 'announcements#hide', as: 'hide_announcement', via: [:get, :post]
  post '/translate/:model/:id', to: 'translations#create', as: :translate

  get '/users/invitation/accept' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('invitation_token=','')}"}
  get '/group_requests/:id/start_new_group' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('token=','')}"}

  get '/contributions' => redirect('/crowd')
  get '/contributions/thanks' => redirect('/crowd')
  get '/contributions/callback' => redirect('/crowd')
  get '/crowd' => redirect('https://love.loomio.org/')
  get '/groups' => redirect('/explore')

  get '/dashboard', to: 'dashboard#show', as: 'dashboard'

  constraints(MainDomainConstraint) do
    scope controller: 'pages' do
      get :about
      get :privacy
      get :purpose
      get :services
      get :terms_of_service
      get :third_parties
      get :try_it
      get :translation
      get :wallets
      get :browser_not_supported
    end
  end

  constraints(GroupSubdomainConstraint) do
    get '/about' => redirect('https://www.loomio.org/about')
    get '/privacy' => redirect('https://www.loomio.org/privacy')
    get '/purpose' => redirect('https://www.loomio.org/purpose')
    get '/services' => redirect('https://www.loomio.org/services')
    get '/terms_of_service' => redirect('https://www.loomio.org/terms_of_service')
    get '/third_parties' => redirect('https://www.loomio.org/third_parties')
    get '/try_it' => redirect('https://www.loomio.org/try_it')
    get '/wallets' => redirect('https://www.loomio.org/wallets')
  end

  scope controller: 'help' do
    get :help
  end

  get '/detect_locale' => 'detect_locale#show'

  resources :contact_messages, only: [:new, :create]
  get 'contact(/:destination)', to: 'contact_messages#new'

  #redirect from wall to new group signup
  namespace :group_requests do
    get 'selection', action: 'new'
    get 'subscription', action: 'new'
    get 'pwyc', action: 'new'
  end

  get '/discussions/:id', to: 'discussions_redirect#show'
  get '/groups/:id',      to: 'groups_redirect#show'
  get '/motions/:id',     to: 'motions_redirect#show'

  get '/users/invitation/accept' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('invitation_token=','')}"}
  get '/group_requests/:id/start_new_group' => redirect {|params, request|  "/invitations/#{request.query_string.gsub('token=','')}"}

  get '/contributions'      => redirect('/crowd')
  get '/contributions/thanks' => redirect('/crowd')
  get '/contributions/callback' => redirect('/crowd')
  get '/crowd'              => redirect('https://love.loomio.org/')

  scope path: 'pages' do
    get 'home'         => redirect('/')
    get 'how*it*works' => redirect('/purpose#how-it-works')
    get 'get*involved' => redirect('/about')
    get 'privacy'      => redirect('/privacy_policy')
    get 'about'        => redirect('/about#about-us')
    match 'contact'    => 'contact_messages#new', via: [:get, :post]
  end

  get '/get*involved'       => redirect('/purpose#how-it-works')
  get '/how*it*works'       => redirect('/purpose#how-it-works')
  get '/about#how-it-works' => redirect('/purpose#how-it-works')

  get '/blog'       => redirect('http://blog.loomio.org')
  get '/press'      => redirect('http://blog.loomio.org/press-pack')

app/controllers/groups/group_setup_controller.rb
class Groups::GroupSetupController < GroupBaseController

  before_filter :load_group
  before_filter :require_current_user_is_group_admin
  before_filter :redirect_to_group_if_already_setup

  def setup
  end

  def finish
    if @group.update_attributes(permitted_params.group)
      @group.mark_as_setup!
      redirect_to @group
    else
      render 'setup'
    end
  end

  private

  def redirect_to_group_if_already_setup
    if @group.is_setup?
      flash[:warning] = t("error.group_already_setup")
      redirect_to @group
    end
  end
end

app/controllers/groups/manage_membership_requests_controller.rb
class Groups::ManageMembershipRequestsController < GroupBaseController
  load_and_authorize_resource :membership_request, only: [:approve, :ignore], parent: false
  before_filter :load_group_and_check_for_response, only: [:approve, :ignore]

  def index
    load_group
    if can? :manage_membership_requests, @group
      @current_requests  = @group.membership_requests.pending
      @previous_requests = @group.membership_requests.responded_to.page(params[:page]).per(7)

      render 'index'
    else
      redirect_to group_path(@group)
      flash[:warning] = t(:'error.access_denied')
    end
  end

  def approve
    ManageMembershipRequests.approve!(@membership_request, approved_by: current_user)
    set_request_approved_flash_message
    redirect_to group_membership_requests_path(@group)
  end

  def ignore
    ManageMembershipRequests.ignore!(@membership_request, ignored_by: current_user)
    flash[:success] = t(:'notice.membership_request_ignored')
    redirect_to group_membership_requests_path(@group)
  end

  private

  def load_group_and_check_for_response
    @group = @membership_request.group
    response = @membership_request.response
    unless response.nil?
      if response == 'approved'
        flash[:warning] = t(:'warning.membership_request_already_approved')
      elsif response == 'ignored'
        flash[:warning] = t(:'warning.membership_request_already_ignored')
      end
      redirect_to group_membership_requests_path(@group)
    end
  end

  def set_request_approved_flash_message
    if @membership_request.from_a_visitor?
      flash[:success] = t(:'notice.membership_approved')+ ' ' +  t(:'notice.new_user_added', user_email_or_name: @membership_request.name)
    else
      flash[:success] = t(:'notice.membership_approved')+ ' ' + t(:'notice.user_added', user_email_or_name: @membership_request.name)
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_visibility_options(group)
    options = []

    unless group.is_subgroup_of_hidden_parent?
      options << [t(:'group_form.visible_to.public_html'), 'public']
    end

    if group.is_subgroup?
      options << [t(:'group_form.visible_to.parent_members_html', parent_group_name: group.parent.name ),
                  "parent_members"]
    end

    options << [t(:'group_form.visible_to.members_html'), "members"]

    options
  end

  def group_joining_options(group)
    if group.is_subgroup_of_hidden_parent?
      [[t(:'group_form.membership_granted_upon.hidden_parent.request_html',
          parent_group_name: group.parent.name),
        'request'],
       [t(:'group_form.membership_granted_upon.hidden_parent.approval_html',
          parent_group_name: group.parent.name),
        'approval'],
       [t(:'group_form.membership_granted_upon.invitation_html'),
        'invitation']]
    else
      [[t(:'group_form.membership_granted_upon.request_html'), 'request'],
       [t(:'group_form.membership_granted_upon.approval_html'), 'approval'],
       [t(:'group_form.membership_granted_upon.invitation_html'), 'invitation']]
    end
  end

  def discussion_privacy_options
    options = [[t(:'group_form.discussion_privacy_options.public_only_html'), "public_only"],
               [t(:'group_form.discussion_privacy_options.public_or_private_html'), "public_or_private"],
               [t(:'group_form.discussion_privacy_options.private_only_html'), "private_only"]]
  end

  def show_next_steps?(group)
    user_signed_in? && current_user.is_group_admin?(group) && !group.next_steps_completed? && @group.is_parent?
  end

  def show_subscription_prompt?(group)
    user_signed_in? && current_user.is_group_admin?(group) &&
      ( group.created_at < 1.month.ago ) &&
      !group.has_subscription_plan? &&
      !group.has_manual_subscription? &&
      !group.is_subgroup?
  end

  def pending_membership_requests_count(group)
    if group.pending_membership_requests.count > 0
      t(:number_pending, pending: group.pending_membership_requests.count)
    else
      ""
    end
  end

  def members_pending_count(group)
    if group.pending_invitations.count > 0
      t(:and_number_pending, pending: group.pending_invitations.count)
    else
      ""
    end
  end

  def join_group_button(group, args = {})
    if user_can_join_group?(current_user_or_visitor, group)
      case group.membership_granted_upon
      when 'request'
        link_to(t(:join_group_btn), join_group_path(group), method: :post, class: "btn btn-block btn-primary btn-left")

      when 'approval'
        if group.pending_membership_request_for(current_user_or_visitor)
          membership_request = group.membership_requests.pending.where(requestor_id: current_user_or_visitor).first
          cancel_membership_request_button(membership_request)
        else
          request_membership_icon_button(group)
        end
      end
    end
  end

  def user_can_join_group?(user, group)
    return true if user.is_logged_out?
    # need to say No if any memberships, suspended or otherwise
    Membership.where(user_id: user.id, group_id: group.id).blank?
  end


  def cancel_membership_request_button(membership_request)
    icon_button(href: cancel_membership_request_path(membership_request),
                method: 'delete',
                text: t(:cancel_membership_request),
                icon: 'group-dark.png',
                id: 'membership-requested',
                class: 'btn btn-block btn-default',
                'data-confirm' => t(:confirm_remove_membership_request))
  end

  def request_membership_icon_button(group, params={})
    old_params = { href: new_group_membership_request_path(group),
                   text: t(:ask_to_join_group),
                   icon: nil,
                   id: 'request-membership',
                   class: 'btn-primary' }
    new_params = old_params.merge(params)
    icon_button(new_params)
  end

  def label_and_description(label, description)
    render('groups/label_and_description', label: label, description: description)
  end

  def user_sees_private_discussions_message?(user, group)
    group.privacy == 'private' &&
    group.members.exclude?(user) &&
    group.discussions.where('private = ?', false).empty?
  end

  def use_parent_if_blank(group, method)
    if group.is_subgroup? && group.send(method).blank?
      group.parent.send(method)
    else
      group.send(method)
    end
  end
end

app/views/groups/_email_members.html.haml
.modal#email-members-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal"}×
        %h3= t :email_members_in_group, which_group: group.full_name
      = form_tag email_members_group_path(group) do
        .modal-body
          .form-group
            = label_tag "group_email_subject", t(:subject)
            = text_field_tag "group_email_subject", nil, :placeholder => t(:subject_placeholder), class: 'form-control'
          .form-group
            = label_tag "group_email_body", t(:message)
            = text_area_tag "group_email_body", nil, :placeholder => t(:message_placeholder, which_group: group.full_name), class: 'form-control'
        .modal-footer
          = submit_tag t(:send_email), class: "btn btn-primary", :data => { :disable_with => t(:send_email) }

app/views/groups/_follow.html.haml
.follow
  - if can? :follow, @group
    - if @group.membership_for(current_user).following_by_default?
      = link_to unfollow_group_path(@group), method: :post, class: "btn btn-default btn-left btn-block js-tooltip cuke-unfollow-group", title: t(:"groups.follow.click_to_unfollow") do
        %i.fa.fa-volume-up
        = t :"common.following"
      %p= t :".following_details"
    - else
      = link_to follow_group_path(@group), method: :post, class: "btn btn-default btn-left btn-block js-tooltip cuke-follow-group", title: t(:"groups.follow.click_to_follow") do
        %i.fa.fa-volume-down
        = t :"common.not_following"
      %p= t :".not_following_details"

app/views/groups/_group_admin_panel.html.haml
.sub-panel#group-admin-panel
  %h4 Admin
  %ul
    %li=link_to 'Edit memberships', group_memberships_path(group)
    %li=link_to 'Pending invitations', group_invitations_path(group)

app/views/groups/_label_and_description.html.haml
%span.described-label
  =label
  %br
  %i= description

app/views/groups/_members.html.haml
- unless group.hide_members && (cannot? :update, group)
  .panel.panel-default#members-panel
    .panel-heading
      %h4
        = t :members
        = "(#{ group.members.count })"

    .panel-body
      %ul#users-list.clearfix
        - group.members.first(15).each do |user|
          %li{:id => user.id}
            = render 'linked_avatar', user: user, show_title: true

    .panel-footer
      .memberships_link
        = link_to t(:more), group_memberships_path(group)

app/views/groups/_membership_requests.html.haml
- if group.membership_requests.where(response: nil).exists? && (can? :add_members, group)

  .panel.panel-default
    .panel-heading
      %h4= t(:membership_requests)
    .panel-body
      = link_to pending_membership_requests_count(group), group_membership_requests_path(group), class: 'bottom-panel-link', id: 'pending-count'

app/views/groups/_setup_next_steps.html.haml
.panel.panel-info#setup-next-steps
  .panel-heading
    %h4
      = t :setup_steps_title
      = link_to("×", hide_next_steps_group_path(@group), method: :post, remote: true, class: "close hide-next-steps")
  .panel-body
    %ol
      %li#example_discussion= t(:setup_step_1)
      %li#first_discussion= t(:setup_step_2)
      %li#invite_people= t(:setup_step_3)

app/views/groups/_subscription_prompt.html.haml
.sub-panel#subscription_prompt
 %h4
  %span.heart-icon ❤
  Pay what you can
 %p Your group has not yet chosen a subscription. You can choose whatever is right for your group, even $0!
 %p
  = link_to "Set up your subscription", group_subscription_path(@group), class: 'bottom-panel-link'

app/views/groups/edit.html.haml
- set_title @group.name, t(:edit_group)
= render '/groups/title', group: @group
.row
  .col-md-6
    %h2= t :edit_group
    = render 'form', group: @group, parent: @parent, submit_text: t(:update_group)

app/views/groups/edit_description.js.erb
$(".long-description").html("<%= j render_rich_text(@description, false) %>")
$(".description-body").show()
$("#description-edit-form").hide()
$(".discussion-description-helper-text").toggle()

app/views/groups/hide_next_steps.js.erb
$('#setup-next-steps').hide();

app/views/groups/new.html.haml
.row
  .col-md-6
    #intro
      %h1 Start your group
      = render 'form', group: @group, submit_text: t(:"common.start_group")

app/views/groups/show.html.haml
- set_title @group.name, "", @group.parent
- cover_photo_url = image_url use_parent_if_blank(@group, :cover_photo).url(:desktop)
- logo_url = image_url use_parent_if_blank(@group, :logo).url(:medium)

.group-heading{style: "background-image: url(#{image_path 'cover-photo-gradient.png'}), url('#{cover_photo_url}')"}
  = render 'application/flash_messages', :flash => flash, :on_landing_page => false
  - if can? :edit, @group
    .upload-button.cover-photo-upload{title: t(:'tooltip.cover_photo_upload')}
      = form_for @group, html: { multipart: true, class: 'js-submit-on-change' } do |f|
        = file_field_tag "group[cover_photo]"
        .edit-icon
          %i.fa.fa-pencil


  .group-logo.hidden-xs{style: "background-image: url('#{logo_url}')"}
    - if can? :edit, @group
      .upload-button.logo-upload{title: t(:'tooltip.logo_upload')}
        = form_for @group, html: { multipart: true, class: 'js-submit-on-change' } do |f|
          = file_field_tag "group[logo]"
          .edit-icon
            %i.fa.fa-pencil

  .group-title
    %h1.home-title.shadow
      - if @group
        - if @group.is_subgroup?
          = link_to @group.parent.name, @group.parent
          = content_tag :span, "\u25B6", class: 'name-separator'
        = link_to @group.name, @group
        = render 'groups/privacy_dropdown', :group => @group
    - if @group.category.present?
      .group-category.shadow.hidden-sm.hidden-xs
        =link_to t(@group.category.translatable_name), category_explore_path(@group.category), title: t(:'tooltip.group_category')

.row
  .col-md-9
    .group-description
      - if (can? :edit, @group) && @group.description.present?
        = link_to edit_group_path @group do
          .edit-icon.edit-description{'data-title' => t(:'tooltip.edit_description')}
            %i.fa.fa-pencil
        .edit-icon-placeholder
      .logo-placeholder.hidden-xs
      ~ render_rich_text(@group.description)
    = render "application/filter_discussions_buttons" if can? :follow, @group
    = render 'discussions/discussion_list'

  .col-md-3
    #group-actions
      .btn-toolbar
      - if can? :create, @discussion
        = link_to new_discussion_path(:group_id => @group.id), class: 'btn btn-block btn-primary btn-left cuke-start-discussion' do
          %i.fa.fa-comments
          = t(:start_a_discussion)
      - if can?(:add_members, @group)
        = render 'invite_button', group: @group, discussion: @discussion
      - if params[:controller] == 'groups' && params[:action] == 'show'
        - can_edit = can? :edit, @group
        - can_leave = @group.users_include? current_user
        - can_archive = can? :edit, @group
        - if can_edit || can_leave
          .btn-group.btn-block.options
            = link_to '#',
                      class: 'btn btn-block btn-default btn-left dropdown-toggle group-options-btn',
                      data: { toggle: 'dropdown' }  do
              %i.fa.fa-cog
              = t :options

            %ul.dropdown-menu.btn-block{role: 'menu'}
              - if can_edit
                %li= link_to t(:edit_group_settings), edit_group_path(@group)
                %li= link_to t(:manage_members), group_memberships_path(@group)

              - if can_leave
                - membership = current_user.group_membership(@group)
                - if @group.is_hidden_from_public?
                  - msg = t(:confirm_leave_hidden_group, which_group: @group.name)
                - else
                  - msg = t(:confirm_leave_group, which_group: @group.name)
                %li= link_to t(:leave_group), group_membership_path(@group, membership), method: 'delete', data: { confirm: msg }

              - if can_archive
                %li= link_to t(:deactivate_group), archive_group_path(@group), method: 'post', data: { confirm: t(:confirm_deactivate_group, which_group: @group.name) }

      = join_group_button(@group)
    = render 'setup_next_steps' if show_next_steps?(@group)
    = render 'follow', group: @group

    = render 'subgroups', group: @group

    - if @closed_motions.any?
      .panel.panel-default.previous-discussions-panel
        .panel-heading
          %h4= t(:previous_decisions)
        .panel-body
          %ul.previous-decisions
            - @closed_motions.first(3).each do |motion|
              %li.previous-decision
                %a.selector-link{ href: motion_path(motion) }
                  .clearfix
                    .pie.motion-sparkline
                      = motion_sparkline(motion)
                    .previous-decision-title.word-break=truncate(motion.name, :length => 60, :separator => ' ')
        .panel-footer
          = link_to t(:see_more), group_motions_path(@group)

    = render 'membership_requests', group: @group
    = render 'members', group: @group